# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import errno
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import time


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(429, 490)
        MainWindow.setMinimumSize(QtCore.QSize(429, 490))
        MainWindow.setMaximumSize(QtCore.QSize(429, 490))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QPushButton{\n"
"    pading: 0px;\n"
"    height: 50px;\n"
"    font-size: 20px;\n"
"    font-weight: 150;\n"
"    font-family: Andale Mono;\n"
"}\n"
"QMainWindow{\n"
"    background-color: #3d3a3a ;\n"
"}\n"
"#dorivnyue{\n"
"    background-color: #07f;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 120, 411, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.seven = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.seven.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seven.setObjectName("seven")
        self.gridLayout.addWidget(self.seven, 1, 0, 1, 1)
        self.six = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.six.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.six.setObjectName("six")
        self.gridLayout.addWidget(self.six, 2, 2, 1, 1)
        self.minus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.minus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minus.setObjectName("minus")
        self.gridLayout.addWidget(self.minus, 2, 3, 1, 1)
        self.five = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.five.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.five.setObjectName("five")
        self.gridLayout.addWidget(self.five, 2, 1, 1, 1)
        self.one = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.one.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.one.setObjectName("one")
        self.gridLayout.addWidget(self.one, 3, 0, 1, 1)
        self.four = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.four.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.four.setAutoDefault(False)
        self.four.setDefault(False)
        self.four.setFlat(False)
        self.four.setObjectName("four")
        self.gridLayout.addWidget(self.four, 2, 0, 1, 1)
        self.plusminus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.plusminus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.plusminus.setObjectName("plusminus")
        self.gridLayout.addWidget(self.plusminus, 4, 0, 1, 1)
        self.cc = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cc.setObjectName("cc")
        self.gridLayout.addWidget(self.cc, 0, 1, 1, 1)
        self.dorivnyue = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(18)
        self.dorivnyue.setFont(font)
        self.dorivnyue.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dorivnyue.setObjectName("dorivnyue")
        self.gridLayout.addWidget(self.dorivnyue, 4, 3, 1, 1)
        self.back = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back.setObjectName("back")
        self.gridLayout.addWidget(self.back, 0, 2, 1, 1)
        self.two = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.two.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.two.setObjectName("two")
        self.gridLayout.addWidget(self.two, 3, 1, 1, 1)
        self.mnozhenya = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mnozhenya.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mnozhenya.setObjectName("mnozhenya")
        self.gridLayout.addWidget(self.mnozhenya, 1, 3, 1, 1)
        self.plus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.plus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.plus.setObjectName("plus")
        self.gridLayout.addWidget(self.plus, 3, 3, 1, 1)
        self.zero = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.zero.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.zero.setObjectName("zero")
        self.gridLayout.addWidget(self.zero, 4, 1, 1, 1)
        self.dilenya = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.dilenya.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dilenya.setObjectName("dilenya")
        self.gridLayout.addWidget(self.dilenya, 0, 3, 1, 1)
        self.nine = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.nine.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nine.setObjectName("nine")
        self.gridLayout.addWidget(self.nine, 1, 2, 1, 1)
        self.three = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.three.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.three.setObjectName("three")
        self.gridLayout.addWidget(self.three, 3, 2, 1, 1)
        self.eight = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.eight.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.eight.setObjectName("eight")
        self.gridLayout.addWidget(self.eight, 1, 1, 1, 1)
        self.koma = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.koma.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.koma.setObjectName("koma")
        self.gridLayout.addWidget(self.koma, 4, 2, 1, 1)
        self.ce = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ce.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ce.setObjectName("ce")
        self.gridLayout.addWidget(self.ce, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 411, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.add_functions()

        self.bag = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.six.setText(_translate("MainWindow", "6"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.five.setText(_translate("MainWindow", "5"))
        self.one.setText(_translate("MainWindow", "1"))
        self.four.setText(_translate("MainWindow", "4"))
        self.plusminus.setText(_translate("MainWindow", "+/-"))
        self.cc.setText(_translate("MainWindow", "C"))
        self.dorivnyue.setText(_translate("MainWindow", "="))
        self.back.setText(_translate("MainWindow", "Назад"))
        self.two.setText(_translate("MainWindow", "2"))
        self.mnozhenya.setText(_translate("MainWindow", "ⅹ"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.dilenya.setText(_translate("MainWindow", "/"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.three.setText(_translate("MainWindow", "3"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.koma.setText(_translate("MainWindow", "."))
        self.ce.setText(_translate("MainWindow", "CE"))

    
    def add_functions(self):
        ui.textBrowser.setText("0")
        ui.zero.clicked.connect(lambda: self.writetxt(ui.zero.text()))
        ui.one.clicked.connect(lambda: self.writetxt(ui.one.text()))
        ui.two.clicked.connect(lambda: self.writetxt(ui.two.text()))
        ui.three.clicked.connect(lambda: self.writetxt(ui.three.text()))
        ui.four.clicked.connect(lambda: self.writetxt(ui.four.text()))
        ui.five.clicked.connect(lambda: self.writetxt(ui.five.text()))
        ui.six.clicked.connect(lambda: self.writetxt(ui.six.text()))
        ui.seven.clicked.connect(lambda: self.writetxt(ui.seven.text()))
        ui.eight.clicked.connect(lambda: self.writetxt(ui.eight.text()))
        ui.nine.clicked.connect(lambda: self.writetxt(ui.nine.text()))
        ui.koma.clicked.connect(lambda: self.kropka("."))
        
        
        ui.dorivnyue.clicked.connect(self.suma)

        ui.ce.clicked.connect(self.delall)

        ui.cc.clicked.connect(self.delall)

        ui.back.clicked.connect(self.backspace)

        ui.plusminus.clicked.connect(self.minusplus)

        ui.plus.clicked.connect(lambda: self.operacyi(ui.plus.text()))
        ui.minus.clicked.connect(lambda: self.operacyi(ui.minus.text()))
        ui.mnozhenya.clicked.connect(lambda: self.operacyi("*"))
        ui.dilenya.clicked.connect(lambda: self.operacyi(ui.dilenya.text()))

    def kropka(self, arg):
        enter = self.textBrowser.toPlainText()
    
        try:
            for symbol in enter:
                if symbol == "+" or symbol == "-" or symbol == "/" or symbol == "*":
                    self.textBrowser.setText(enter + "0" + arg)
                else: 
                    self.textBrowser.setText(enter + arg)
        
        except Exception as ex:
            error = QMessageBox()
            error.setWindowTitle("Помилка")
            error.setText("Некоректний приклад!")
            error.setIcon(QMessageBox.Warning)
            error.exec_()

    def operacyi(self, arg):
        enter = self.textBrowser.toPlainText()
        for symbols in enter:
        
            if symbols == "+" or symbols == "-" or symbols == "/" or symbols == "*":
                self.textBrowser.setText(enter[:-1] + arg)
            elif symbols == ".":
                self.textBrowser.setText(enter + "0" + arg)    
            else:
                self.textBrowser.setText(enter + arg)


    def minusplus(self):
        enter = ui.textBrowser.toPlainText()
        if enter[0] == "-":
            ui.textBrowser.setText(enter[1:])
        else:
            ui.textBrowser.setText("-" + enter)

    def writetxt(self, num):
        if ui.textBrowser.toPlainText() == "0" or self.bag:
            ui.textBrowser.setText(num)
            self.bag = False
        else:
            ui.textBrowser.setText(self.textBrowser.toPlainText() + num)
    
    def suma(self):
        if not self.bag:
            try:
                res = eval(self.textBrowser.toPlainText())
                self.textBrowser.setText(str(res))
                self.bag = True
            except ZeroDivisionError:
                error1 = QMessageBox()
                error1.setWindowTitle("Помилка")
                error1.setText("На 0 ділити не можна!")
                error1.setIcon(QMessageBox.Warning)
                error1.exec_()
        else:
            error = QMessageBox()
            error.setWindowTitle("Помилка")
            error.setText("Щось пішло не так!")
            error.setIcon(QMessageBox.Warning)
            error.exec_()


    def delall(self):
        ui.textBrowser.setText("0")
    
    def backspace(self) -> None:
        entry = self.textBrowser.toPlainText()

        if len(entry) != 1:
            if len(entry) == 2 and '-' in entry:
                self.textBrowser.setText('0')
            else:
                self.textBrowser.setText(entry[:-1])
        else:
            self.textBrowser.setText('0')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
